name: template_matching
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  audioplayers: ^6.1.0
  flutter:
    sdk: flutter
  flutter_sound: ^9.17.8
  onnxruntime: ^1.4.1
  path_provider: ^2.1.5
  record: ^5.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/models/model.onnx
    - assets/audio/references/dog.pcm
    - assets/audio/references/cat.pcm
    - assets/audio/references/mouse.pcm