name: speech_recognition
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  audioplayers: ^6.1.0
  sherpa_onnx: ^1.10.34

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/audio/audio1.wav
    - assets/audio/audio2.wav
    - assets/audio/audio3.wav
    - assets/models/tiny-encoder.int8.onnx
    - assets/models/tiny-decoder.int8.onnx
    - assets/models/tiny-tokens.txt
